pr: none # Disable pull request triggers.

trigger:
  branches:
    include:
      - master

stages:
  - stage: arm
    pool:
      name: arm
      vmImage: 'Ubuntu-20.04'

    ## Job to create release and add tag
    jobs:
      - job: Release
        displayName: Release
        variables:
          - group: wahalla-kds
        steps:
          # Checkout with persist credentials
          - checkout: self
            persistCredentials: true

          - task: Docker@2
            displayName: Login to KMEE registry
            inputs:
              command: login
              containerRegistry: 'kmee-registry'

          - task: Bash@3
            displayName: 'Build'
            inputs:
              targetType: inline
              script: |
                VERSION=12.0-buster make build
                VERSION=12.0-buster TAG=latest make push
